packages:
  - "."
  - "client"

allowBuilds:
  "@prisma/engines": true
  better-sqlite3: false
  esbuild: true
  prisma: true

minimumReleaseAgeExclude:
  - "@types/node@24.19.1"

overrides:
  deepmerge-ts: ^8.0.2
  mysql2: ^3.24.5
